[ep]
cogpath = "."  # Relative to the current file
socket_emit = true
socket_channel = 634044757328265225
superusers = [633557681277239296, 431627389492264970]

[[ep.tui.filters."MESSAGE_CREATE".exclude]]
author.id = "633625526736519178"
channel_id = "634044757328265225"

[default]
guild_snowflake = 633621230024523776
guild_member_role = 633623354657472522
guild_bot_role = 633624610272837642

tagging.repository = "https://github.com/mental32/ep.tagging"

captcha.enabled = false

projects.index_channel_id = 654009312829767680
projects.category_id = 653936235466719252
projects.hosts = ["github\\.com", "gitlab\\.com"]

resource.file_limit = 0x700000
resource.channel_id = 653906357950480384
# git://, http:// and https:// are all valid paths, provided they are git repositories.
# Otherwise any path is a filepath relative to the resolving source file.
resource.paths = [
    "git://github.com/mental32/ep.resources",
    "./knowledge/Python/"
]

banner.entries = [
    "category://633624313043353620",
    "Total members: {guild.member_count}",
    "{now.strftime('%a, %d %b %Y %H:%M')}"
]
