[ep]
cogpath = "."  # Relative to the current file
socket_emit = true
socket_channel = 634044757328265225
superusers = [633557681277239296, 431627389492264970]

# `default` specific config values.
guild_snowflake = 633621230024523776

banners = [
    "category://633624313043353620",
    "Total members: {guild.member_count}",
    "Server time: {now.strftime('%H:%M')}"
]
